import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Head from "./head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <Head/>
      <body className={'w-full max-w-[1100px] mx-auto text-sm sm:text-base min-h-screen flex flex-col ' + inter.className}>
        <Header />
        { children }
        <Footer />
      </body>
    </html>
  );
}
